### ISSUE TITLE
Disappearing dividers since last update

### ISSUE THREAD

**Issue by dmantisk** [andrewmcgivery/obsidian-ribbon-divider#8]
Some dividers randomly disappear when minimizing/switching windows/restarting app.
Have to delete and add the dividers again.

This issue was not present previously.

![image](https://github.com/andrewmcgivery/obsidian-ribbon-divider/assets/113114365/11c2fe0b-02d5-4c1d-a596-55e6fcf39fa5)

**Comment by sisi-sh** [comment]
Second, having this on latest everything, and still happens in sandbox. Creating multiple dividers and moving one causes all to disappear, moving some around can cause others to arbitrarily disappear, etc. Not sure about a reliable method to reproduce it just happens every time lol

Started within the last month, in which 1.5.8+ insider updates happened? 

edit: pulling and freezing 1.0.0 via BRAT still works

**Comment by andrewmcgivery** [comment]
Apologies, been super busy!

This should be fixed in version 1.1.1. Please update to latest and restart Obsidian. :)

If you are still having issues, please open another issue!

Thank you for reporting!
